
Vagrant.configure("2") do |config|

    config.vm.box = 'ubuntu/bionic64'
    config.vm.hostname = 'manager'
    config.vm.network "private_network", ip: "192.168.1.2"
    config.vm.synced_folder ".", "/home/vagrant/vagrant", type: "nfs", mount_options: ['vers=3','tcp']
    config.vm.provision "shell", inline: "hostnamectl set-hostname manager"
    config.vm.provider "virtualbox" do |v|
      v.memory = "2048"
    end
  
  end
  