
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.synced_folder ".", "/home/vagrant/vagrant", type: "nfs", mount_options: ['vers=3','tcp']
  config.vm.provision "shell", path: "provision.sh"
end
