# 192.168.56.106
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.synced_folder "~/devops/ansible-lab/control-node/playbooks", "/home/vagrant/vagrant"
end
