- name: Upgrade de todos os pacotes do s.o
  apt:
    name: "*"
    state: latest
- name: Instalacao do git client
  apt:
    name: git
    state: latest
- name: Configurar hosts lab ansible
  lineinfile: 
    dest: /etc/hosts
    state: present
    line: "{{item}}"
  with_items:
     - 192.168.1.2 control-node
     - 192.168.1.3 app01
     - 192.168.1.4 db01