mysql_root_password: devops
mysql_databases:
  - name: app
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: springapp
    host: "%"
    password: devops
    priv: "app.*:ALL"