
Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    config.vm.hostname = "app01"
    config.vm.network "private_network", ip: "192.168.56.3"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
  
  end
  